name: Build
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '2.7', '3.6', '3.9' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: 3.14

      - name: Install wheel
        run: pip install wheel

      - name: Install NumPy
        run: pip install --prefer-binary numpy

      - name: Build
        run: python setup.py bdist_wheel

      - name: Install
        run: pip install dist/velodyne_decoder-*.whl

      - name: Test import
        run: python -c "import velodyne_decoder"
